watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"

bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 4
      left: 8
      bottom: 0
      right: 8
    widgets:
      left: ["taskbar", "komorebi_workspaces", "komorebi_active_layout"]
      center: ["active_window"]
      right: ["volume", "memory", "cpu", "clock"]

widgets:
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      show_only_visible: false
      strict_filtering: false
      monitor_exclusive: false

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[app_name]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: false
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span> {%H:%M}"
      label_alt: "<span>\uf017</span> {%A %d %B %Y, %H:%M}"
      timezones: []

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf4bc</span> {info[percent][total]}%"
      update_interval: 2000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_free}"
      label_alt: "<span>\uefc5</span> {virtual_mem_percent}%"
      update_interval: 10000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\udb81\udd81" # muted
        - "\uf026" # 0-10%
        - "\uf027" # 11-30%
        - "\uf027" # 31-60%
        - "\uf028" # 61-100%
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "\u25cf"
      label_workspace_active_btn: "\u25cf"
      label_workspace_populated_btn: "\u25cf"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: true
      hide_if_offline: false
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STK"
        horizontal_stack: "H-STK"
        ultrawide_vertical_stack: "W-STK"
        right_main_vertical_stack: "RMV"
        monocle: "MONO"
        maximised: "MAX"
        floating: "FLT"
        paused: "PAUSE"
      callbacks:
        on_left: "next_layout"
        on_middle: "toggle_monocle"
        on_right: "prev_layout"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
